### ISSUE TITLE
Improve receiveMessage on createServer

### ISSUE THREAD

**Issue by StNekroman** [delight-rpc/worker-threads#5]
```
receiveMessage?: (data: unknown) => IRequest<unknown> | IBatchRequest<unknown> | undefined;
```
As I understood here I can hook all incomming calls and process them manually.
It's good, but not enough.

In my use case I want filter api calls and accept calls only to public methods (I use TypeScript, so I'll just create whitelist of method names) and hide private methods from client's eyes and client's access completely.
But using `receiveMessage` I need deal with everything myself, what I want avoid.
I don't want to know, how IReqest & IBatch request processing is done, which edge cases possible and everything.
I just want to have ability to call default implementation.
The implementation, which is called when `receiveMessage` is not defined.

With that I can just whitelist methods (pass events to default impl) and just ignore possible rest.

**Comment by StNekroman** [comment]
Use case is next:
```typescript
class ApiImpl {
    public publicMethod(id: string) {
          // do some validation and permission checking
         this.deleteThing(id);
    }

    private deleteThing(id: string) {
         // do work directly
    }
}
```

Via RPC client can access deleteThing, becuase in JS no `private` keyword exists.
If own client side - that's ok, I trust myself, I guess.
But I run untrusted code in sandbox and provide there an API.

As workarounds (without implemeting this ticket) there are next options:
1) process incomming events manually
2) 
Do something like:
```typescript
function deleteThing(id) {
   // do work
}

function ApiImplFacory() {

    return {
         publicMethod: (id) => {
                // validation
               deleteThing(id);
         }
    } as Api;
}
```
and that is ugly

**Comment by BlackGlory** [comment]
First, JavaScript supports private fields, please read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

Second, it is not recommended that you expose classes directly to arbitrary clients as APIs, which is a very bad design.
Please create a separate API class like this:
```ts
class API implements ImplementationOf<IAPI> {
   // ...
}
```

**Comment by StNekroman** [comment]
So intead of just 
```
return createServer(new ApiImpl(...), port)
```

you suggest me

```
const api = new ApiImpl(...);
const proxyApi = {
    deleteThing: (id) => api.deleteThing(id),
    // + long list of other public methods
} as Api;
return createServer(proxyApi, port);
```
?

**Comment by BlackGlory** [comment]
Yes, there are many benefits to separating the API from the internal implementation.
The most important is that it helps to comply with [dependency inversion principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle).

**Comment by BlackGlory** [comment]
Also, I suggest you reduce the use of `as` in TypeScript, your usage is incorrect.
It should be:
```ts
const proxyApi: IAPI = {
    deleteThing: (id) => api.deleteThing(id),
    // + long list of other public methods
};
```
or
```ts
const proxyApi: ImplementationOf<IAPI> = {
    deleteThing: (id) => api.deleteThing(id),
    // + long list of other public methods
};
```

**Comment by BlackGlory** [comment]
If you use the `bind` in my [extra-proxy](https://www.npmjs.com/package/extra-proxy), or any similar helper function, it can be even simpler.
```ts
const impl = new Impl()
const boundImpl = bind(impl)
const api: ImplementationOf<IAPI> = {
  deleteThing: boundImpl.deleteWhatever
  // Only add validators when you need them
}
```

**Comment by BlackGlory** [comment]
The more OOP approach:
```ts
interface IAPI {
  deleteThing(id: string): boolean
}

class Impl {
  // ...
}

class API implements ImplementationOf<IAPI> {
  #instance: Impl

  constructor(implementation: Impl) {
    this.#instance = implementation
  }

  deleteThing(id) {
    return this.#instance.deleteWhatever(id)
  }
}

const impl = new Impl()
createServer(new API(impl), port)
```
